name: CI/CD with Docker, Nginx and SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-static-site .

      - name: Save Docker image to file
        run: |
          docker save my-static-site > my-static-site.tar

      - name: Copy image to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          source: "my-static-site.tar"
          target: "/home/${{ secrets.SSH_USER }}/deploy/"

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            # Опционально: удаляем предыдущий образ
            docker stop my-site || true
            docker rm my-site || true
            docker rmi my-static-site || true

            # Загружаем новый образ
            docker load -i /home/${{ secrets.SSH_USER }}/deploy/my-static-site.tar

            # Запускаем контейнер
            docker run -d --name my-site -p 80:80 my-static-site